# configServer.yaml
# Config file for the config mongod replica set instances
# author:     inf20133@lehre.dhbw-stuttgart.de
# date:       04.05.2023
# version:    1.0.0

systemLog:
  destination: file
  path: /var/log/mongodb/mongodConfig.log
  logAppend: true
storage:
  dbPath: /var/lib/mongodb/configS
net:
  port: 27019
  bindIp: 0.0.0.0
sharding:
  clusterRole: configsvr
replication:
  replSetName: RTDSconfig
