# routerServer.yaml
# Config file for the mongos instances
# author:     inf20133@lehre.dhbw-stuttgart.de
# date:       04.05.2023
# version:    1.0.0

systemLog:
  destination: file
  path: /var/log/mongodb/mongosRouter.log
  logAppend: true
net:
  port: 27017
  bindIp: 0.0.0.0
sharding:
  configDB: RTDSconfig/n1:27019,n2:27019,n3:27019
