# shardServer2.yaml
# Config file for the shard2 mongod replica set instances
# author:     inf20133@lehre.dhbw-stuttgart.de
# date:       04.05.2023
# version:    1.0.0

systemLog:
  destination: file
  path: /var/log/mongodb/mongodShard2.log
  logAppend: true
storage:
  dbPath: /var/lib/mongodb/shardS2
net:
  port: 27020
  bindIp: 0.0.0.0
sharding:
  clusterRole: shardsvr
replication:
  replSetName: RTDSshard2
