systemLog:
  destination: file
  path: /var/log/mongodb/mongodShard1.log
  logAppend: true
storage:
  dbPath: /var/lib/mongodb/shardS1
net:
  port: 27018
  bindIp: 0.0.0.0
sharding:
  clusterRole: shardsvr
replication:
  replSetName: RTDSshard1
