# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile
# Vagrant script for automatically creating/destroying the virtual infrastructure
# author:     inf20133@lehre.dhbw-stuttgart.de
# date:       04.05.2023
# version:    1.0.0

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define "un" do |un|
    un.vm.provider "virtualbox" do |vb_un|
      vb_un.name = "Node 1"
      vb_un.memory = 4096
      vb_un.cpus = 4
    end

    un.vm.box =  "ubuntu/focal64"
    un.vm.hostname = "un"
    un.vm.boot_timeout = 1000
    un.vm.network "public_network", bridge: "Realtek USB GbE Family Controller #3", ip: "192.168.10.201"

    un.trigger.after :up do |trigger|
      trigger.run_remote = {inline: "bash /vagrant/initNode.sh"}
    end
  end

  config.vm.define "dos" do |dos|
      dos.vm.provider "virtualbox" do |vb_dos|
        vb_dos.name = "Node 2"
        vb_dos.memory = 4096
        vb_dos.cpus = 4
      end

      dos.vm.box =  "ubuntu/focal64"
      dos.vm.hostname = "dos"
      dos.vm.boot_timeout = 1000
      dos.vm.network "public_network", bridge: "Realtek USB GbE Family Controller #3", ip: "192.168.10.202"

      dos.trigger.after :up do |trigger|
        trigger.run_remote = {inline: "bash /vagrant/initNode.sh"}
      end
    end

  config.vm.define "tres" do |tres|
        tres.vm.provider "virtualbox" do |vb_tres|
          vb_tres.name = "Node 3"
          vb_tres.memory = 4096
          vb_tres.cpus = 4
        end

        tres.vm.box =  "ubuntu/focal64"
        tres.vm.hostname = "tres"
        tres.vm.boot_timeout = 1000
        tres.vm.network "public_network", bridge: "Realtek USB GbE Family Controller #3", ip: "192.168.10.203"

        tres.trigger.after :up do |trigger|
          trigger.run_remote = {inline: "bash /vagrant/initNode.sh && /vagrant/initMongoDBServers.sh"}
        end
      end

  # Adding RSA public key to VM
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
  end

end
